# Generated by Django 3.2.13 on 2023-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_image',
            field=models.ImageField(default='', upload_to='cat_img/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
