# Generated by Django 3.2.13 on 2023-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230604_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagte4',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagte4',
            name='image1',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagte4',
            name='image2',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagte4',
            name='image3',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagte4',
            name='image4',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='imagte4',
            name='image5',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
