# Generated by Django 3.2.13 on 2023-05-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_top_image'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoTanla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='2 Category')),
            ],
        ),
    ]
